CREATE DATABASE HomeworkSQL4;

USE HomeworkSQL4;

CREATE TABLE dbo.Lessons (
	Id INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	Title NVARCHAR(500),
	Description NVARCHAR(MAX)
);

CREATE TABLE dbo.Members (
	Id INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	Name NVARCHAR(500),
	GithubAccount NVARCHAR(500)
);

CREATE TABLE dbo.TimeCode (
	Id INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	LessonID INT NOT NULL,
	MemberID INT NOT NULL,
	Title NVARCHAR(500),
	TIMESTAMP TIME
);

CREATE TABLE dbo.Questions (
	Id INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	LessonID INT NOT NULL,
	MemberID INT NOT NULL,
	Title NVARCHAR(500),
	TIMESTAMP TIME
);
